### ISSUE TITLE
bug: NoClassDefFoundError ApplicationExitInfo on API 24-29 at plugin load (8.46.0+), regression after #756

### ISSUE THREAD

**Issue by gilperon** [riderx/capacitor-updater#780]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 8.3.4
  @capacitor/core: 8.3.4
  @capacitor/android: 8.3.4
  @capacitor/ios: 8.3.4

Installed Dependencies:

  @capacitor/cli: 8.3.4
  @capacitor/core: 8.3.4
  @capacitor/android: 8.3.4
  @capacitor/ios: 8.3.4

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Plugin Version

```
●   Web Dir: dist
●   Node: v24.9.0

Installed Dependencies:
●     @capgo/capacitor-updater: 8.46.1   ← version where bug was reproduced
●     @capgo/capacitor-admob: 8.1.5
●     @capgo/capacitor-app-tracking-transparency: 8.1.7
●     @capgo/capacitor-health: 8.4.10
●     @capgo/capacitor-pedometer: 8.0.32
●     @capgo/capacitor-social-login: 8.3.22

Also tested: 8.46.0 (same crash). Works on 8.45.11 / 8.45.3 (no ApplicationExitInfo in plugin class).
```

### context(s)

```md
ManualModel: false
AutoMode: true
CapgoCloud: false
OnPremise: true
```

### Platform(s)

- Android (native)
- API levels **24–29** (confirmed on **API 28**; `ApplicationExitInfo` exists only from **API 30+**)
- iOS not affected by this specific crash (Android-only class loading issue)

### Current Behavior

With `@capgo/capacitor-updater` **8.46.0** or **8.46.1**, the app **crashes immediately on cold start** on Android devices **API 28 and below**.

**Logcat:**

```
java.lang.NoClassDefFoundError: Failed resolution of: Landroid/app/ApplicationExitInfo;
   at com.getcapacitor.Plugin.initializeActivityLaunchers(Plugin.java:109)
   at com.getcapacitor.PluginHandle.loadInstance(PluginHandle.java:116)
   at com.getcapacitor.Bridge.registerPlugin(Bridge.java:705)
```

`Plugin.java:109` is misleading — it runs `getDeclaredMethods()` while loading `CapacitorUpdaterPlugin`. The real failure is **class loading**: `CapacitorUpdaterPlugin` references `android.app.ApplicationExitInfo` (API 30+), which does not exist on API ≤ 29.

In **8.46.x**, `CapacitorUpdaterPlugin.java` has:

- `import android.app.ApplicationExitInfo;`
- `reportPreviousAppExitReasons()`, `statsActionForApplicationExitReason()`, `buildApplicationExitMetadata(ApplicationExitInfo)` with `ApplicationExitInfo.REASON_*` in switches

There is a runtime guard in `reportPreviousAppExitReasons()`:

```java
if (Build.VERSION.SDK_INT < Build.VERSION_CODES.R) { return; }
```

but it **never runs** because the class **fails to load** before any method executes.

**Production impact:** Play Store users on older Android cannot open the app after shipping a build with 8.46.x.

### Expected Behavior

Plugin should load and run on all API levels supported by `minSdkVersion` **24**, consistent with **8.45.x**.

Exit-reason reporting via `ApplicationExitInfo` should only run on **API 30+**, without referencing that type in the main plugin class bytecode on older APIs (separate class, reflection, or similar).

### Code Reproduction

1. Create or use any Capacitor 8 app with `@capgo/capacitor-updater@8.46.1`
2. `npx cap sync android`
3. Run on emulator/device **API 28** (Android 9) or **API 26–27**
4. Launch app → immediate crash (stack trace above)

**Verify:**

```bash
grep -n "ApplicationExitInfo" \
  node_modules/@capgo/capacitor-updater/android/src/main/java/ee/forgr/capacitor_updater/CapacitorUpdaterPlugin.java
```

- **8.46.1:** matches found → crash on API ≤ 29
- **8.45.11:** no matches → app starts

### Other Technical Details

`npm --version` output: **11.6.0**

`node --version` output: **v24.9.0**

`pod --version` output: **1.16.2**

| Package | Version when bug occurred | Notes |
|---------|---------------------------|--------|
| `@capgo/capacitor-updater` | **8.46.1** (introduced in **8.46.0**) | Root cause |
| `@capacitor/android` | 8.3.4 | Does **not** reference `ApplicationExitInfo` |
| `@capacitor/core` | 8.3.4 | — |

**Workaround:**

```bash
npm install @capgo/capacitor-updater@8.45.11
npx cap sync android
```

`8.45.11` keeps `PackageInfoCompat.getLongVersionCode()` from #756 and removes `ApplicationExitInfo`.

### Additional Context

**Related (previous issue — fixed, different bug):**

- https://github.com/Cap-go/capacitor-updater/issues/755 — `NoSuchMethodError` for `PackageInfo.getLongVersionCode()` on API 26–27
- https://github.com/Cap-go/capacitor-updater/pull/756 — merged May 5, 2026 — `PackageInfoCompat` fix

We upgraded from **8.45.3 → 8.46.1** to get the #756 fix. That fixed API 26–27 `getLongVersionCode`, but **8.46.x added `ApplicationExitInfo` without API-safe class loading**, breaking API 24–29.

**Suggested fix:**

- Move `ApplicationExitInfo` / `getHistoricalProcessExitReasons` into a class loaded only on API 30+ (reflection or factory), **or** use reflection with no direct import on `CapacitorUpdaterPlugin`
- Add regression test / CI that plugin loads on **API 28**
- Patch release **8.46.2+** appreciated

Thanks!

**Comment by riderx** [comment]
please try https://github.com/Cap-go/capacitor-updater/actions/runs/26154950996 8.46.3
